---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  values:
    image:
      repository: ghcr.io/dmitriysafronov/dummy-backend # {"$imagepolicy": "dummy-backend:dummy-backend:name"}
      tag: main-5066572-1704290656347 # {"$imagepolicy": "dummy-backend:dummy-backend:tag"}
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: dummy.lab-testing.home.arpa
          paths:
            - pathType: Prefix
              path: "/api"
      tls:
        - hosts:
            - dummy.lab-testing.home.arpa
          secretName: dummy-backend-tls
