---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  url: ssh://git@github.com/DmitriySafronov/fleet-infra.git
  interval: 5m0s
  ref:
    branch: master
  secretRef:
    name: dummy-frontend-git-auth
