apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  image: registry.cyberbrain.pw/tools/docker/dummy-frontend
  interval: 1m0s
