apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  image: registry.cyberbrain.pw/tools/docker/dummy-frontend
  interval: 10m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  suspend: false
  sourceRef:
    kind: GitRepository
    name: dummy-apps
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Flux
        email: root@cyberbrain.pw
      messageTemplate: '[ci skip] update image: dummy-frontend'
  interval: 10m0s
  update:
    strategy: Setters
