apiVersion: v1
kind: Service
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  selector:
    app: dummy-backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
