apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dummy-backend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
