apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  template:
    spec:
      containers:
      - name: dummy-frontend
        image: registry.cyberbrain.pw/tools/docker/dummy-frontend:0.0.4 # {"$imagepolicy": "dummy-frontend:dummy-frontend-lab"}
