apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  template:
    spec:
      containers:
      - name: dummy-frontend
        image: ghcr.io/dmitriysafronov/dummy-frontend:0.0.6 # {"$imagepolicy": "dummy-frontend:dummy-frontend-lab"}
