apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  interval: 10m
  url: https://dmitriysafronov.github.io/helm-charts
