apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  values:
    nameOverride: dummy-frontend
    image:
      repository: registry.cyberbrain.pw/tools/docker/dummy-frontend
    containerPort: 8080
    deploymentType: Deployment
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
    podSecurityContext:
      fsGroup: 1000
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
    livenessProbe:
      httpGet:
        path: /
        port: default
      periodSeconds: 10
      failureThreshold: 5
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: default
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - dummy-frontend
            topologyKey: "kubernetes.io/hostname"
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 50
      targetMemoryUtilizationPercentage: 50
    tmp:
      enabled: true
