apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  sourceRef:
    kind: GitRepository
    name: dummy-apps
  git:
    checkout:
      ref:
        branch: main
    push:
      branch: main
    commit:
      author:
        name: Flux
        email: root@cyberbrain.pw
      messageTemplate: "Image update automation: dummy-backend [ci skip]"
  interval: 10m0s
  update:
    path: ./base/_template_dummy-backend
