---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  values:
    nameOverride: dummy-backend
    containerPort: 3000
    deploymentType: Deployment
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
    podSecurityContext:
      fsGroup: 1000
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
    livenessProbe:
      httpGet:
        path: /api
        port: default
      initialDelaySeconds: 30
      failureThreshold: 5
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /api
        port: default
      failureThreshold: 3
      periodSeconds: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - dummy-backend
              topologyKey: "kubernetes.io/hostname"
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 50
      targetMemoryUtilizationPercentage: 50
