---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - image-policy.yaml
  - image-repository.yaml
  - image-update-automation.yaml
  - sync.yaml
patches:
  - path: patch_helm-release.yaml
