apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  interval: 10m
  url: https://dmitriysafronov.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  interval: 10m
  chart:
    spec:
      chart: default
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: dummy-frontend
