apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: dummy-frontend-lab
  namespace: dummy-frontend
spec:
  imageRepositoryRef:
    name: dummy-frontend
  policy:
    semver:
      range: '>=0.0.1'
