apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  chart:
    spec:
      version: 0.8.4
  values:
    image:
      repository: ghcr.io/dmitriysafronov/dummy-frontend # {"$imagepolicy": "dummy-frontend:dummy-frontend-lab-test:name"}
      tag: main-e85e664-1704216824591 # {"$imagepolicy": "dummy-frontend:dummy-frontend-lab-test:tag"}
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
        cert-manager.io/cluster-issuer: "letsencrypt"
      className: nginx
      hosts:
      - host: dummy.lab-test.cyberbrain.pw
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: dummy-frontend
              port:
                number: 80
      tls:
      - hosts:
        - dummy.lab-test.cyberbrain.pw
        - www.dummy.lab-test.cyberbrain.pw
        secretName: dummy-frontend-tls
