apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  chart:
    spec:
      version: 1.1.0
  values:
    image:
      repository: ghcr.io/dmitriysafronov/dummy-frontend # {"$imagepolicy": "dummy-apps-merged:dummy-frontend:name"}
      tag: 0.0.41 # {"$imagepolicy": "dummy-apps-merged:dummy-frontend:tag"}
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: dummy.lab-staging.home.arpa
          paths:
            - pathType: Prefix
              path: "/"
              backend:
                service:
                  name: dummy-frontend
                  port:
                    number: 80
      tls:
        - hosts:
            - dummy.lab-staging.home.arpa
          secretName: dummy-frontend-tls
