apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: dummy-frontend-lab-test
  namespace: dummy-frontend
spec:
  imageRepositoryRef:
    name: dummy-frontend
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^main-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
