apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  update:
    path: ./overlays/lab-testing/dummy-backend-manifests
