apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  chart:
    spec:
      version: 0.9.0
  values:
    image:
      repository: ghcr.io/dmitriysafronov/dummy-frontend # {"$imagepolicy": "dummy-apps-merged:dummy-frontend:name"}
      tag: main-efb7c3a-1732124202407 # {"$imagepolicy": "dummy-apps-merged:dummy-frontend:tag"}
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      className: nginx
      hosts:
        - host: dummy.lab-testing.cyberbrain.pw
          paths:
            - pathType: Prefix
              path: "/"
              backend:
                service:
                  name: dummy-frontend
                  port:
                    number: 80
      tls:
        - hosts:
            - dummy.lab-testing.cyberbrain.pw
          secretName: dummy-frontend-tls
