apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  values:
    image:
      repository: ghcr.io/dmitriysafronov/dummy-frontend # {"$imagepolicy": "dummy-apps-merged:dummy-frontend:name"}
      tag: main-8ec8620-1734538443704 # {"$imagepolicy": "dummy-apps-merged:dummy-frontend:tag"}
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: dummy.lab-testing
          paths:
            - pathType: Prefix
              path: "/"
              backend:
                service:
                  name: dummy-frontend
                  port:
                    number: 80
      tls:
        - hosts:
            - dummy.lab-testing
          secretName: dummy-frontend-tls
