---
name: Yamllint on pull request to main
"on":
  pull_request:
    branches: [main]
jobs:
  yamllint:
    name: Yamllint on pull request to main
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_file_or_dir: '.'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
